# Generated by Django 2.0.3 on 2018-03-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_num', models.IntegerField(blank=True, unique=True)),
                ('passing_year', models.IntegerField()),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('duration', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni')),
                ('photos', models.ManyToManyField(to='alumni.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.Courses'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.Branches'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
